### PR TITLE
continuum mechanics chapter

### PR DESCRIPTION
**Pull request by gwslingerland**
i am adding the continuum mechanics chapter as listed in the concept toc.

Continuum mechanics

1.  Model
- Stresses in 3D
- Isotropic and deviatoric components
- Strains in 2D

2. Transformations
-  Analytical
-  Graphical

3. Stress-strain relations
4. Failure

### CODE REVIEW

**Comment by Tom-van-Woudenberg** [comment]
@gwslingerland , could you add this to the TOC too?

**Comment by gwslingerland** [comment]
@Tom-van-Woudenberg , I added them to the TOC.

**Review by Tom-van-Woudenberg — APPROVED** [review]
I did some changes, thanks again!

**Comment by Tom-van-Woudenberg** [comment]
I'll add these to the other book @gwslingerland

**Pull request merged**
